### ISSUE TITLE
No such file or directory: 'README.md' at install

### ISSUE THREAD

**Issue by justhamade** [raff/dynash#6]
When running pip install on OS X
```
Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-QFmSai/dynash/setup.py", line 21, in <module>
        long_description = open("README.md").read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by raff** [comment]
Should be fixed (but for the life of my I can't test it. "pip" insists of picking the wrong version from pypi.python.org).

Let me know if you still have problem. Also, try easy_install (that's what I normally use so I never saw this problem before)
